### PR TITLE
Support for RSRs on macOS

### PR DESCRIPTION
**Pull request by grahamgilbert**
```
osquery> select * from macos_rsr;
+-------------+---------------+--------------------+---------------+
| rsr_version | macos_version | full_macos_version | rsr_supported |
+-------------+---------------+--------------------+---------------+
| (a)         | 13.3.1        | 13.3.1 (a)         | true          |
```

### CODE REVIEW

**Review by zwass — COMMENTED** [review]
Thank you for doing this! I'd love to ship it with the new fleetd version going out today.

**Comment by erikng** [comment]
What does rsr supported mean in this context?

**Review by erikng — APPROVED** [review]
Figured out my question from the last comment

**Comment by Oneiroi** [comment]
For posterity in relation to @erikng 's question above (as thi may in the future show up in a search result); 

RSR = "Rapid Security Response" 

This first occurred with macOS version 13.3.1 applying RST version 'a' ; 

the intent from Apple here is to be able to push our security releases separate to the normal update flow carrying improvements and bugfixes for macOS, further information w.r.t RST's can be found on [this](https://support.apple.com/en-gb/HT201224) page (hopefully some reader in the future will find this useful).

**Comment by Oneiroi** [comment]
13.4.1a has been [withdrawn](https://support.apple.com/en-us/HT213827) 13.4.1b is to be released "soon"

**Pull request merged**
